/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mendykjanniktontauben;

import java.awt.Graphics;

/**
 *
 * @author Jannik.Mendyk
 */
public class Oberflaeche extends javax.swing.JPanel {

    /**
     * Creates new form GUI
     */
    
    private int xFK;
    private int yFK;
    Steuerung steuerung;
    
    
    public Oberflaeche() {
        System.out.println("of");
        initComponents();
        steuerung = new Steuerung(this);
        setFocusable(true);
        requestFocus();
    }
    
    
    public void geklicktMaus(){
       int x = getX();
       int y = getY();
       
       steuerung.feuer(x, y);
    }
    
    public void paintComponents(Graphics g){
        System.out.println("paintCom");
        g.drawRoundRect(getX(),getY(),30,30,30,30); 
        System.out.println(getX());
        zeichnen(g);
    }
    
    public void zeichnen(Graphics g){
        
        steuerung.zeichneAlleTt(g);
    }
    
    public void zeigeBildFertig(){
        
    }
    
    public void spielStart(){
        steuerung.starteSpiel();
    }
    
    public void aktualisiereOberflaeche(){
        repaint();
    }
    
    
    public int gibXFK(){
        
        return xFK;
    }
    
    public int gibYFK(){
        
        return yFK;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        geklicktMaus();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
